travis:
  secure:
    BINSTAR_TOKEN: DkSkG8G4yNEozvTvLmLsyto0ULV6T7T1k0fI5FX8w1LVXeaUWivkj2Hr6tW657SSLE9rzjjlQF9I2xUAIUbhkCH5rJv/9QgT1aykgivfSaJPb8Jz29M31Qxv2OUTLWG1Y2moj+Rhm/C2JNIb26t3x4qVmpKgakDCNjLDIuun4mWTiRNOan9LgNMg06aDRA3W1cdTfJmjE/4HQTZi4rJzHDfEFY+KrrDBIKM6B8pDLvnXIZAnbMcBccS53J048h+Do2kmHNK+/vOSZ5etaQxUHY6eAscvM45Al63acEzWRhw78INOO4SfMasXmZy7TPk5BrJbj3LR7BtgPifQOfdNAGnW11srHdODdFITr0I85TQIdqkHzdvz+2eauvqG6oRoni8TXINPNg6H6VQ3gWkvdq8poLguroeXG82Vj9zQRsm6odFVlzbP3mt1ZhSxuieoPyZwwSokNvOOf/ADXuAyKNH93xAO3Ds+ztxHVPMjkQxPBphiBphJf/e+ggzD+9AZCqwdVjVnCJEExk2kiu/ZGU4augapbRKtToM8th6ClEA0uVsXwS16ODGUdW0+k61GZvrnSRTGK2igHhNsCf1vvl/FAKKzxm07Me737TWqVu2xslGphdsYHMKrBPmf+LPKYFimn5IPlyIi9S+BPmD3KVHv3IPQm0OBJAkAr4N87/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
