travis:
  secure:
    BINSTAR_TOKEN: cmZVeCklM9OZUiHpA7yZ9ooUoe3RbHELAX4Vk48DbEzbQrx3EQmf3AWz2NVa8gTaWFiDUgtConIDZqfyr/Wdq2xkbow/SeVYrnevbVIkq7XSMbWp4XazDtrtPwOG1+URwZUEibummrjMr78p5o1hiYj1TIeQ3gOHzAgzhit3SQUBuizL1V98BmEQMX5bc6AhuEdfmSfCDjMWpC3giQC+g3+dGB6BccH0ohjGrCBoQFoIkerFyAtYmc8H51SbDZjhNLyrmLMkgHSIOLzAiGURuBDYOSoTLPMr39AwQLbEXNFi9vJsdaSgP7sFuywtiKGX5y9DAPOIeRs/s4EzPmLfIsHWlPHO24FBwLOj61dCExeOMe/D5zz+hSzPILduGsLEk+ukLk5/l48i+e/lxtUTRN7JBxVNYBYj0nul1GCfi76QsZylKm1wwAS9Cg2Lf6g2vSWWJJHtksdWIpLJJFRvRDs65P9GhZsAyPeedk1SuT6XiK26yLayXzBYJj1bWewZk2ynxiLbR2e7oOpCqPKK+MzWeJ8VJhMzcDYGuPAOou+JGZDbPPLEd5gfjyQz6xLpZHFACkLwZpMUC/q+RyJ1PCLlTLvZK0sAWRq4K73SXhs+z+CqHLSMxqtJXTH7D+D+NDJojToZdTwtO4d4HgsZv3d+Ho6LMcCEPAojisAJPqs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
