travis:
  secure:
    BINSTAR_TOKEN: LaDYOjPOW82VbcwNj5QsBXbrI+UNUE12l3B2tpfFFcxFQ8Uj3oe7t/I8ElwxdxIvxgQb1VrvIbuUn9bQbGr2wiLfEUvfiBETE5QTK96I2wgUvzvU0kLqeF0UYQM0W3C47iLLtJWXUMeQ7lCHbwpOT938CI4MGRt5p3MLIYiw0bHFnrLrC5kZg1sEU3OfEPgOCdpb+dGZWOqvlLgHRlB4qi0bw/HSYcJ7QpMKxhScNPd44RQaCIlVjx5WijfsCJHlfLMdmsxO/lPAF1rMPQAzB3oS2GBYykChZkh/OTk15E7JGLzGYN98jq59E9+ryyu8+GQ8Z0EOcPx2HHE6kuf6ZB4y67L8i6yPCopWGi7yG1JdRPIbr/kpBOhqUJRl/4I6ma9qrcjDTk4fLV7y3aqbYvfuIgF4ObbXs1DNXO4mnCJEXQUrvho6e5Y2lnMaScPPpM238DP69pZCM7kPBvv5IfHO6dHDznrUqwzuvFn54QiNBULCC2lYNb6DMVbFLhZ2eiPqdMUQjhP5b+Lenngm6m+ybjJgkdmmfQMcKdEV+BUAo5z0IImgLt4fx0GuWKP5e5MYCYMpwH+AI849rRCu7q7jZRHzwRok6MgLp3BqINLQKMutPVTnoQ35W3iHR0pqaGuVPzCtLhg3XJAkXXzVAKMx0Zqpac5NxapD1654TBE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
