appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: CPEZXwnqmHraVvmtKHvFmHZxUqwROCHsM1jaTp9kdH9BBaPIn79hK56eaZz8O3usqGJjpnMV6cPM9cEpv5pP8nKXkoFa+mzXI9fCVSs/ezyo6+vFx0Cxq0lzQmwqLaOnLwWavPO+VX53U/lWkK8SZVhYoZtsRbrsf+L7PXLyq06/07e0e/fkLpKconGZfbsBRSCNqo36NcSCkyFa+frg9390nbSqlwDW1U7aA8rio1GpgP9kBnQvpj209r54r2Bd5fkJ4qDgAcIk+gT+QN3nmUFchsYNC7mgH8xJJ7N5ZEvB1hir4CqC/gPf6h4C10qqDTaOcQrZfQgOVZu0CEr1F3DXZ+pLkffI56V9fgfmAUkUQzB3chFg8Y78ckBUXgq7Vc6MYJpSgH1OF2GS8jHfWuCvyE0fhRWyBWaI05h73yLDtbpK+wsqT1VXT4r0taxJwzcwupu+8fMpN6+MLkAiFEJaygfevMbqVfYGzTcNwy0zLxfOdgqY1zjkFk7E8TdnKKIyFivKSIMjbO0C0Sk7hlBdNz/oJk1jWGrGaTK0qYy1wehNFjZoFJHffAC9zC+yiZkP468IabtcuHymwsk8i7unIopDGG/cPtJRVQSZlo/8lENMxKhricSsKPhscRniuTndwsLw2icAQhd/8zsjDHaEXNw1Qkp1+3fJIl/fOvo=}
