travis:
  secure:
    BINSTAR_TOKEN: oZbBr69d/EAN+/cOZbi77SLTTv7kSnF0yo8rZrTh3Tnc+ulmg1IWb+2EmrWBxzT1hJA1zuVU0pOWpipDuSwEndV5Xq5fo9ca9Yp7q0UqDW3IXPHCa+XxeuGKXKHtjahYb4KXRGvUdVIgOgfG3KZTMftRAZRfMAiCL65GqQwdCL3R95pSSFTSQPRLEqHKd5s5rcAkq8z8lRscJhXKzRH8UMFbbfbi8NCDrkgXr0ArbhKugnm6uH2N/s2ee4TNpUtuSih6dkoaumI/3NQrvlXZdN3E2u061SAlFnf/T1uoV7U7cbMZIBT7B5b3bMDZzfBK6xxPePIE3mJcU5gSk5UB3A2VpKqC+juLUFtMueiBBS8BMQsUXSmOA2ygwqEIZAkx8+2pPVFCSftdL6+VDkEUvaKRIxEbYRYMDCY20H7VMbMWDoMZ6SNn8zf504O/CTwD9XJFIhaOKguQm1sy0rcirFWVrflfL63ge6xvE00/EkPUGxb7Mpta3S2KrHfVS3+Y4iDLzJlC5k2nRMRQ5Ksr/pPBcVWETHOHfbRdlsuTmg59+TjCQnnf+0ovXndII2gxqEiboXfvwvkMDK0NpxkBSTW6UFrpOeVKj722XGuWrtnmzHLj9P31+YGRggYEcvf9N1GZQC/TTrZIOJTQNaIM3TNDnxMkfJxbsPcU5Ci5E/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
