travis:
  secure:
    BINSTAR_TOKEN: PkhHeKxrkIqdkkU42EWpZecBLJ2baUdMq3PpSJVXXXR5HVg16dQXWQhcmLKq7RTTaSMfj76IIZNecYbdm79ey7LuO7CGtLWD4jZtl7eB/pLiSrSqp+6jsY4R/7ojjLuLIsIUOKr7tPZ4ebn2RDmQORNPCjgtM90DROnBenTxS4jjElygzeY2ENFLT/EJZjahzy7qF+u33bEXWUKVWfbr0Itqiwh1yronJUMgPsjr92gwN2kzKgVgcD+yK8MTAObqWFuA555WVyRj6ELpThAM8/Dmxl23gZr2v9JHG+TEqEnx2mqFSk6UoXCwDjAMoJkQUHV+/hbigMd1Ph6tDhYCNT8LUagYumwEW7ZUuw3D/iGe4kJd5HDxEHbw9NUPUYvbfT7ZLN47XbIrM+bb1FTaQj/yO1kMvEFIAz3cBSl58NB7blPyXd8q64NFh8uw4JqfvxANONHI3rVKcOY+lZSoS3fYMKJUzkes0jso6/hYcc76utMf0KX18855upKbsXM/gImpjlH6SUJzaD2Jp2rhIuvSY0hkZE+j7h0Q+EQq1z3npP2T9xths+yU6MsvcdsQXmeHMDeXa0VZRvabKbqY2tPzI7UC7QO7vE/aixLUdKZjcx/3NWhv6YxzyH/pz17dFb8abvTbuVgv6XWCEXVyhG63/Su5AI4tDfEnwYuMm+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
